var MoooR=getCookie_Liscom("AAAAAAAAdSense");
  if(MoooR < 11){  
document.write("<div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/19/index.htm>开关电源和电源</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/20/index.htm>传感器控制技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/21/index.htm>气体放电灯电源</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/22/index.htm>高低电压逆变技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/23/index.htm>本站制作电源技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/24/index.htm>电器维修技术经验</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/25/index.htm>单片机编程及应用</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/26/index.htm>电子小制作技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/27/index.htm>电子电路基础</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/29/index.htm>电子应用技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/33/index.htm>电工基础知识</a></div><div><font face=wingdings color=#FF00FF><B>1</B></font><a href=/165v/list/31/index.htm>电子实用电路</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/34/index.htm>手机技术和维修</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/28/index.htm>数据通信载波技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/30/index.htm>音响功放音箱技术</a></div><div><font face=wingdings color=#FF00FF><B>1</B></FONT><a href=/165v/list/32/index.htm>简易电子电源制作</a></div>");
} else if(MoooR == ""){
location.href("http://www.165v.com/405.htm");
} else if(MoooR > 11111111111111111111){
location.href("http://www.165v.com/500.htm");
} else {
document.write("<div style='font-size:14px;color:#FF0000;font-weight:bold'>　最新出版：电压控制型-开关电源驱动模块PM4040F<A HREF='http://www.165v.com/pdf/pm4040.pdf' TARGET='_blank'>（PDF技术资料下载）</a>更加强大的驱动能力，直接驱动300A的IGBT和120A的MOS管，1KW到5KW的开关电源制作更简单。2007.06.09</div><br><iframe id='baiduframe' border='0' vspace='0' hspace='0' marginwidth='0' marginheight='0' framespacing='0' frameborder='0' scrolling='no' width='140' height='75' src='http://unstat.baidu.com/bdun.bsc?tn=165v&cv=0&cid=64186&csid=105&rkcs=0&bgcr=FFFFFF&ftcr=0000CC&rk=1&bd=1&tbsz=&tbst=&bdas=0'></iframe>");
}

